# Generated by Django 3.0.8 on 2020-08-02 11:04

from django.db import migrations, models
import django.db.models.deletion
import mainapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comic_name', models.CharField(max_length=500, verbose_name='название комикса')),
                ('comic_description', models.TextField(blank=True, max_length=4000, verbose_name='описание комикса')),
                ('comic_author', models.CharField(blank=True, max_length=250, verbose_name='автор комикса')),
                ('comic_artist', models.CharField(blank=True, max_length=250, verbose_name='работающие над комиксом(Artist)')),
                ('comic_genre', models.CharField(help_text='Abstract, Adult, Hentai', max_length=100, verbose_name='категория комикса')),
                ('comic_total_chapters', models.CharField(blank=True, default='Unknown', max_length=100, verbose_name='всего глав комикса')),
                ('comic_type', models.CharField(blank=True, default='Comic', max_length=100)),
                ('comic_status', models.CharField(blank=True, default='Ongoing', help_text='Ongoing, Ended, ...', max_length=100, verbose_name='статус комикса')),
                ('comic_original_name', models.CharField(blank=True, default='None', help_text='For Manga/Manhua/Manhwa', max_length=100)),
                ('comic_banner_image', models.FileField(help_text='лицо комикса', upload_to=mainapp.models.comic_banner_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=mainapp.models.images_directory_path)),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Comic')),
            ],
        ),
    ]
