# Generated by Django 3.0.8 on 2020-08-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='comic_artist',
            field=models.CharField(max_length=250, verbose_name='работающие над комиксом(Artist)'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='comic_author',
            field=models.CharField(max_length=250, verbose_name='автор комикса'),
        ),
    ]
