# Generated by Django 3.0.8 on 2020-08-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_bookmarkcomic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarkcomic',
            name='page_number',
            field=models.IntegerField(blank=True),
        ),
    ]
