# Generated by Django 3.0.8 on 2020-08-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20200809_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarkcomic',
            name='page_number',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
