# Generated by Django 3.0.8 on 2020-08-20 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20200809_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comic',
            name='comic_original_name',
        ),
        migrations.RemoveField(
            model_name='comic',
            name='comic_status',
        ),
        migrations.RemoveField(
            model_name='comic',
            name='comic_total_chapters',
        ),
        migrations.RemoveField(
            model_name='comic',
            name='comic_type',
        ),
        migrations.AddField(
            model_name='comic',
            name='comic_original_link',
            field=models.URLField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='comic',
            name='comic_artist',
            field=models.CharField(default=models.CharField(max_length=250, verbose_name='автор комикса'), max_length=250, verbose_name='работающие над комиксом(Artist)'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='comic_genre',
            field=models.CharField(choices=[('ht', 'Hentai'), ('ad', 'Adult'), ('mr', 'Marvel'), ('dc', 'DC'), ('At', 'Another')], default='At', max_length=2, verbose_name='категория комикса'),
        ),
    ]
