# Generated by Django 3.0.8 on 2020-08-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20200820_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='comic_genre',
            field=models.CharField(choices=[('ht', 'Hentai'), ('dk', 'Dark'), ('ad', 'Adult'), ('mr', 'Marvel'), ('dc', 'DC'), ('at', 'Another')], default='at', max_length=2, verbose_name='категория комикса'),
        ),
    ]
