# Generated by Django 3.0.8 on 2020-10-01 01:29

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('mainapp', '0007_auto_20200826_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='comic_artist',
            field=models.CharField(default='', max_length=250, verbose_name='работающие над комиксом(Artist)'),
        ),
    ]
