# Generated by Django 3.0.8 on 2020-08-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comicreader',
            name='adult_comic',
            field=models.BooleanField(null=True, verbose_name='Для взрослых'),
        ),
        migrations.AlterField(
            model_name='comicreader',
            name='age',
            field=models.PositiveIntegerField(default=16, verbose_name='возраст'),
        ),
        migrations.AlterField(
            model_name='comicreader',
            name='darck_comic',
            field=models.BooleanField(null=True, verbose_name='Темное'),
        ),
        migrations.AlterField(
            model_name='comicreader',
            name='dc_comic',
            field=models.BooleanField(null=True, verbose_name='Вселенная DC'),
        ),
        migrations.AlterField(
            model_name='comicreader',
            name='hentai_comic',
            field=models.BooleanField(null=True, verbose_name='hentai'),
        ),
        migrations.AlterField(
            model_name='comicreader',
            name='marvel_comic',
            field=models.BooleanField(null=True, verbose_name='Вселенная Marvel'),
        ),
    ]
