# Generated by Django 3.0.8 on 2020-08-09 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_bookmarkbase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookmarkBase',
        ),
    ]
