# Generated by Django 3.0.8 on 2020-08-16 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_delete_bookmarkbase'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicreader',
            name='is_uploader',
            field=models.BooleanField(default=False, verbose_name='Uploader'),
        ),
    ]
