# Generated by Django 3.0.8 on 2020-10-15 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_comicreader_is_uploader'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicreader',
            name='theme',
            field=models.CharField(default='white_theme', max_length=250, verbose_name='Тема интерфейса'),
        ),
    ]
